<!doctype html>
<html>
<head class=" js csstransforms3d">
    <meta charset="utf-8">
    <title>进销存管理系统</title>
</head>
<body>
<div class="superWrap clearfix" style="height: 781px">
    <div class="super-header super-header2">
        <iframe src="doHeader" id="Pubheader" name="Pubheader" width="100%" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>
    </div>

    <div class="super-side-menu">
        <iframe src="public_left" width="205" height="100%" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>
    </div>
    <div class="superContent">
        <div class="superCtab superCtabBot" style="height: 695px;">
            <iframe src="doCommodity" id="Mainindex" name="Mainindex" width="100%" height="100%" marginheight="0" marginwidth="0" frameborder="0"></iframe>
        </div>
    </div>
</div>
</body>
<link rel="stylesheet" type="text/css" href="/css/base.css">
<link rel="stylesheet" type="text/css" href="/css/page.css">
</html>
