<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>公共侧边栏</title>
</head>

<body>
	<!--side S-->
	<div class="super-side-menu">
		<div class="side-menu">
			<ul>
				<li>
					<a href="doCommodity" target="Mainindex">
						<i class="ico-6">
						</i>首&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;页
					</a>
				</li>
				<li><a href="doSale" target="Mainindex"><i class="ico-1"></i>销售管理</a></li>
				<li><a href="doStock" target="Mainindex"><i class="ico-2"></i>库存管理</a></li>
				<li><a href="doStockgood" target="Mainindex"><i class="ico-3"></i>进货管理</a></li>
				<li><a href="doLoss" target="Mainindex"><i class="ico-4"></i>报损管理</a></li>
				<li><a href="xinxipandian" target="Mainindex"><i class="ico-5"></i>信息盘点</a></li>
			</ul>
		</div>
	</div>
	<!--side E-->

</body>
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/page.css">
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/modernizr.js"></script>
</html>