<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>信息盘点</title>
</head>

<body>
<div class="superCtab">
    <div class="ctab-title clearfix">
        <h3>信息盘点</h3>
    </div>
    <div class="ctab-Mian-cont">
        <div class="Mian-cont-btn clearfix">
            <h class="BsearchText1">按商品编号查询：</h>
            <div class="BsearchBar1">
                <input type="text" id="" value="" class="form-control srhTxt" placeholder="输入商品编号">
                <input type="button" class="srhBtn" value="">
            </div>
            <h class="BsearchText2">按报损日期查询：</h>
            <div class="BsearchBar2">
                <input type="date" id="" value="" class="form-control srhTxt">
                <input type="button" class="srhBtn" value="">
            </div>
        </div>

        <div class="Mian-cont-wrap">
            <div class="defaultTab-T">
                <table border="0" cellspacing="0" cellpadding="0" class="defaultTable">
                    <tbody>
                    <tr>
                        <th class="t_1">序号</th>
                        <th class="t_2">商品编号</th>
                        <th class="t_3">盈亏</th>
                        <th class="t_4">报损比</th>
                        <th class="t_7" colspan="2">操作</th>
                    </tr>
                    </tbody>
                </table>
            </div>
            <table border="0" cellspacing="0" cellpadding="0" class="defaultTable defaultTable2">
                <tbody>
                <tr>
                    <td class="t_1" style="left:9px;">20150084</td>
                    <td class="t_2">B101</td>
                    <td class="t_3" style="left:9px;">2020-07-06</td>
                    <td class="t_4" style="left:9px;">7</td>
                    <td class="t_7" colspan="2">
                        <div class="btn">
                            <a href="#" class="detail" style="margin-left:30px;">详情</a>
                        </div>
                    </td>
                </tr>

                </tbody>
            </table>
            <!--pages S-->
            <div class="pageSelect">
                <span>共 <b>188</b> 条 每页 <b>10 </b>条   1/18</span>
                <div class="pageWrap">
                    <a class="pagePre"><i class="ico-pre">&nbsp;</i></a>
                    <a href="#" class="pagenumb cur">1</a>
                    <a href="#" class="pagenumb">2</a>
                    <a href="#" class="pagenumb">3</a>
                    <a href="#" class="pagenext">
                        <i class="ico-next">&nbsp;</i>
                    </a>
                </div>
            </div>
            <!--pages E-->
        </div>


    </div>
</div>

</body>
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/page.css">
</html>
